version: '3.8'

services:
    dev:
        container_name: tempo-api_dev
        image: tempo-api-dev:0.0.1
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3001:3000
            - 9230:9229
        networks:
            - nesjs-incorp-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: tempo-api-prod
        image: tempo-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3001:3000
            - 9230:9229
        networks:
            - nesjs-incorp-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-incorp-network:
